### ISSUE TITLE
NameError: global name 'DEBUG' is not defined

### ISSUE THREAD

**Issue by alanjaouen** [jk4837/ShowDefinitionEx#5]
When opening the console:

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 478, in run_callback
    expr()
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 717, in <lambda>
    run_callback('on_hover', callback, lambda: callback.on_hover(v, point, hover_zone))
  File "C:\Users\ajaouen\AppData\Roaming\Sublime Text 3\Installed Packages\ShowDefinitionEx.sublime-package\ShowDefinitionEx.py", line 564, in on_hover
    if DEBUG:
NameError: global name 'DEBUG' is not defined

**Comment by jk4837** [comment]
Hi alanJaouen,

I have release new version 1.0.10 for this bug.
Thanks for reporting.
